### ISSUE TITLE
Copy to bincrafters?

### ISSUE THREAD

**Issue by ghost** [jgsogo/conan-portaudio#12]
Hi Javier,

Would you mind if I copy this package over to bincrafters? It might be nice if we can have it there together with the others. It would also increase its chances of making it to conan-center 😄

**Comment by ghost** [comment]
Hello again Javier,

I had a bit of time this weekend, so I have now applied the bincrafters templates to portaudio and published it on bincrafters:

https://github.com/bincrafters/conan-portaudio

https://bintray.com/bincrafters/public-conan/portaudio%3Abincrafters

I've pushed the history to the repository so both our contributions are visible:

https://github.com/bincrafters/conan-portaudio/commits/stable/v190600.20161030

**Comment by jgsogo** [comment]
I still don't know how bincrafters work, no one has explained it to me.

Here in this repo I keep track of several versions and a master one, all of them are properly handled in the commit story, so we can easily adapt to (incompatible/improvement) changes in conan behaviour and be able to generate portaudio packages for every version.

The way bincrafters repos generate packages doesn't take care of this issue, do they?

**Comment by ghost** [comment]
Hi Javier,

Bincrafters also have one branch per library version. So, if there is a breaking change in the conan executable, each package version can be updated accordingly on each branch. The difference is that there is no master branch and the trunk of the library(master) is never packaged. Only stable, released versions of each library get a branch and are packaged.
Other than that, bincrafters provide some pretty well made .travis, .travis.yml appveyor.yml, build.py and test_package files that work unchanged for all packages. For the README, and conanfile.py they provide templates and I must say that the results in all my packages where I applied their proposed changes were quite good, with greater variety of builds that have even helped me expose problems with my packages that I wouldn't have otherwise seen (like errors when cross-building 32 bit executables on 64 bit linux machines or builds that didn't correspond in effect to their conan parameters).
It's true that I learned most things about how bincrafters work by chatting on cpplang.slack.com (bincrafters channel), but there's an effort to centralise the documentation now: https://github.com/bincrafters/community
